src/commerce/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout')
]

src/commerce/commerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('accounts/', include('accounts.urls')),
]

src/commerce/store/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views
from . import api

app_name = 'store'

# Routers provide a way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'products', api.ProductViewSet)
router.register(r'orderproduct', api.OrderProductViewSet)
router.register(r'orders', api.OrderViewSet)
router.register(r'ordersbyuser', api.OrderByUserViewSet)
router.register(r'productsbyorder', api.ProductByOrderViewSet)
router.register(r'paidorder', api.PaidOrderViewSet)


urlpatterns = [
    path('api/', include(router.urls)),
    path('', views.index, name='index'),
    path('myorders', views.orders, name='myorders'),
    path('report', views.report, name='report'),
]

src/commerce/accounts/models.py
from django.db import models

# Create your models here.

src/commerce/store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import signals


class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    image = models.TextField()
    price = models.IntegerField()
    quantity = models.IntegerField()


class Order(models.Model):
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now_add=True, blank=False)
    total = models.IntegerField()
    payment = models.IntegerField()
    fullpayment = models.BooleanField()


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()


def save_product(instance, update_fields, **kwargs):
    prod = Product.objects.get(pk=instance.product_id)
    prod.quantity = prod.quantity-instance.quantity
    prod.save()


signals.pre_save.connect(save_product, OrderProduct)

src/commerce/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('/')

src/commerce/store/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request, 'store/store.html')


@login_required
def orders(request):
    return render(request, 'store/orders.html')


@login_required
def report(request):
    return render(request, 'store/report.html')

src/commerce/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <h1>Ingresar</h1>

    <form action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
        <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
        {% endfor %}
        </p>
        {% endfor %}
        <input type="submit" class="btn btn-success" value="Ingresar">
    </form>
</div>
{% endblock content %}

src/commerce/templates/accounts/signup.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <h2>Registrarse en E-Commerce</h2>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
        <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
        {% endfor %}
        </p>
        {% endfor %}
        <button type="submit" class="btn btn-success">Registrarse</button>
    </form>
</div>
{% endblock content %}

src/commerce/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">

    {% block extra_css %}
    {# Override this in templates to add extra stylesheets #}
    {% endblock extra_css %}
    <title>E-Commerce</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">E-Commerce</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/myorders">Mis Compras</a>
                    </li>
                    {% if user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="/report">Reporte General API</a>
                    </li>
                    {% endif %}

                </ul>
                <span class="navbar-text">
                    {% if user.is_authenticated %}
                    <form action="{% url 'accounts:logout' %}" method="post">
                        Hola, <strong class="text-capitalize me-4">{{ user.get_username }}</strong>
                        {% csrf_token %}
                        <button class="btn btn-primary btn-sm me-4" type="submit">Salir</button>
                    </form>
                    {% else %}
                    <a href="/accounts/login" class="btn btn-primary btn-block" style="color:white">Ingresar</a>
                    <a href="/accounts/signup" class="btn btn-primary btn-block" style="color:white">Registrarse</a>
                    {% endif %}
                </span>
                <span class="navbar-text ms-3 me-5">
                    <button type="button" class="btn btn-success btn-block" data-bs-toggle="modal"
                        data-bs-target="#cart" onclick="buildOrderList()">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                            class="bi bi-cart-check" viewBox="0 0 16 16">
                            <path
                                d="M11.354 6.354a.5.5 0 0 0-.708-.708L8 8.293 6.854 7.146a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z">
                            </path>
                            <path
                                d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z">
                            </path>
                        </svg>
                        <text id="orderitems">0</text>
                    </button>
                </span>
            </div>
        </div>
    </nav>

    <!-- Content -->
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <!-- End - Content -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    {% block extra_js %}
    {# Override this in templates to add extra javascript #}
    {% endblock extra_js %}
</body>

</html>

src/commerce/templates/store/orders.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<h1>Mis Compras</h1>

<main class="container" id="orders">
    <div class="fs-2 mb-3 d-flex justify-content-center align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-cart-x"
            viewBox="0 0 16 16">
            <path
                d="M7.354 5.646a.5.5 0 1 0-.708.708L7.793 7.5 6.646 8.646a.5.5 0 1 0 .708.708L8.5 8.207l1.146 1.147a.5.5 0 0 0 .708-.708L9.207 7.5l1.147-1.146a.5.5 0 0 0-.708-.708L8.5 6.793 7.354 5.646z">
            </path>
            <path
                d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z">
            </path>
        </svg>
        <h1>Aún no has realizado compras …</h1>
    </div>

</main>

<div class="fs-2 mb-3 d-flex justify-content-center align-items-center">
    <a href="/" class="btn btn-primary btn-block btn-lg" style="color:white">Ir a comprar</a>
</div>



{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'js/order.js' %}"></script>

<script>
    let userid = {{ user.id| safe }}
</script>

{% endblock extra_js %}

src/commerce/templates/store/report.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<h1>Ordenes Pagadas</h1>

<main class="container" id="orders">

</main>

<nav aria-label="Page navigation" class="mt-5">
    <ul class="pagination justify-content-center" id="pageitems">

    </ul>
</nav>

{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'js/report.js' %}"></script>

{% endblock extra_js %}

src/commerce/templates/store/store.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link href="{% static 'css/store.css' %}" rel="stylesheet" />
{% endblock extra_css %}

{% block content %}

<main class="grid" id="products">

</main>


<nav aria-label="Page navigation" class="mt-5">
    <ul class="pagination justify-content-center" id="pageitems">

    </ul>
</nav>


<!-- Modal -->
<div class="modal fade " id="cart" tabindex="-1" aria-labelledby="cartLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered  modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="cartLabel">CARRITO DE COMPRAS</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {% if user.is_authenticated %}
                <div class="container" id="orderlist"></div>
                {% else %}
                <h5>Hola, para continuar con tu compra, inicia sesión </h5>
                <a href="/accounts/login" class="btn btn-primary btn-block" style="color:white">Ingresar</a>
                <h5>o crea una cuenta </h5>
                <a href="/accounts/signup" class="btn btn-primary btn-block" style="color:white">Registrarse</a>
                {% endif %}
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="saveorder" disabled onclick="saveOrder()"
                    data-bs-dismiss="modal">Guardar
                    Orden</button>
                <button type="button" class="btn btn-primary" id="pay" disabled onclick="pay()"
                    data-bs-dismiss="modal">Pagar</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Continuar comprando</button>
            </div>
            <div class="modal-footer">
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="Pago parcial" aria-label=""
                        id="partialpaymentbox" aria-describedby="button-addon2">
                    <button class="btn btn-secondary" type="button" id="partialpayment" disabled
                        onclick="partialpayment()">Pago Parcial</button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->

{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'js/store.js' %}"></script>

<script>
    let userid = {{ user.id| safe }}
</script>


{% endblock extra_js %}